import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';
import { Toaster } from '@/components/ui/toaster';
import { ConvexClientProvider } from '@/lib/ClerkConvexProvider';
const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ConvexClientProvider>
          {' '}
          <NavBar /> {children} <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
